on:
  workflow_dispatch:

jobs:
  build_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Clone leveldb submodules
        run: |
          cd inc/leveldb
          git submodule update --init --recursive

      - name: Install C/C++ requirements
        run: |
          sudo apt update
          sudo apt install -y gcc g++ cmake

      - name: Compile
        run: |
          cd inc/leveldb
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "compile leveldb"
          git push
